### PR TITLE
feat(component): add once method

### PR DESCRIPTION
**Pull request by mixed**
## Issue
Ref #412

## Details
once is executed event just one time.

## Preferred reviewers
@happyhj @jongmoon

### CODE REVIEW

**Comment by mixed** [comment]
@jongmoon 
Yes. We have to comply coding convetion. Why is my code wrong?

**Comment by jongmoon** [comment]
@mixed As below.

https://github.com/naver/egjs/pull/434/files#diff-36f2c7f7bbf377bdc2b3eacfa9332396R431

```js
  ok( callCount, 1); //TOBE: ok(callCount, 1);
```

https://github.com/naver/egjs/pull/434/files#diff-36f2c7f7bbf377bdc2b3eacfa9332396R390

```js
test("once method should be fire event one time.",function(){ // space is need before function()
```

**Comment by mixed** [comment]
@jongmoon 
Ah.... Thanks.  I agree with you but currently Coding covention applied only source code. What do you think discuss this issue at next offline meeting?

**Comment by jongmoon** [comment]
@mixed no problem!

I think there would be many uncomplied source code.

**Pull request merged**
