### PR TITLE
chore(all): support jsdoc setting to support ko tag

### PR DESCRIPTION
**Pull request by jongmoon**
## Issue
#271

## Details
Support markdown on @ko Tag in jsdoc documentation

like below,
```html
/**
 * @ko 안녕하세요! **굵은글씨**도 가능하고 이미지도 연결 할 수 있어요 ![YourImage](http://....)
 */
```

## Preferred reviewers
@sculove @naver/egjs-dev

### CODE REVIEW

**Comment by mixed** [comment]
👍

**Comment by sculove** [comment]
Could you support `param` tag?

**Comment by sculove** [comment]
I found this [page](https://github.com/naver/egjs-jsdoc-template/wiki/%EC%A3%BC%EC%84%9D%EC%97%90-%EB%A7%88%ED%81%AC%EB%8B%A4%EC%9A%B4-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
thanks. LGTM

**Comment by jongmoon** [comment]
@sculove param can be supported as you found. But custom tag <ko>  for `param` can not be. It should be developed in another thread. 

I will apply this pr first.

**Pull request merged**
