### PR TITLE
Panel number have to change on 'flickEnd' event

### PR DESCRIPTION
**Pull request by netil**
## Issue

#219 

## Details

Changed to alter panel's index and no, to be only on _setPanelNo() method.
Added _getNumByDirection() to get pos/neg according direction
Added _revertPanelNo() in case of revert to previous position
Changed _triggerEvent() to pass previous index/no on non 'flickEnd' events

## Preferred reviewers

@sculove @mixed

### CODE REVIEW

**Comment by sculove** [comment]
When flicking is moving, methods of flicking should return exactly value.
ex) getElement method should return current element at `flick` event.

**Comment by netil** [comment]
I'll re

**Comment by sculove** [comment]
LGTM

**Comment by mixed** [comment]
👍

**Pull request closed without merging**
