### PR TITLE
Upgrade infiniteGrid#10

### PR DESCRIPTION
**Pull request by sculove**
## Details
- add append/prepend events
- add threshold option
- add croppedCount parameter in layoutComplete event

## Referrence
 - I couldn't test prepend mode because of #68. if that is complete, I will add testcase
#10 

## Preferred Reviewer
@kishu @mixed

### CODE REVIEW

**Comment by mixed** [comment]
LGTM

**Comment by mixed** [comment]
LGTM

**Comment by kishu** [comment]
LGTM

I want you to consider make cache that result of this.getBottomElement(), this.getTopElement() in _onScroll

**Comment by kishu** [comment]
LGTM

**Pull request closed without merging**
