### PR TITLE
chore(.gitignore): add `/` postfix for directories

### PR DESCRIPTION
**Pull request by sculove**
## Issue
#252 

## Details
add `/` postfix to prevent some issues.

## Preferred reviewers
@naver/egjs-committers

### CODE REVIEW

**Comment by jongmoon** [comment]
LGTM

**Comment by kishu** [comment]
FYI

See https://www.gitignore.io/api/bower%2Cnode%2Cosx%2Cwebstorm
It it `gitignore` service most people used. Typically, in that case 'directory' does not contains end with a shash.

Here is `gitignore` guide https://git-scm.com/docs/gitignore. I'm not sure it contains a slash is better. 
Let me know the issues that caused without slash.

**Comment by sculove** [comment]
We face a problem at 1.2.0 release.
if `/` postfix is nothing, git decide to just pattern.
if you want to check a definite directory, you should add `/` postfix.

Plz check this chapter https://git-scm.com/docs/gitignore#_pattern_format

**Comment by kishu** [comment]
I got it~
LGTM!

**Pull request merged**
