### PR TITLE
docs(readme) : Clarifying file inclusion

### PR DESCRIPTION
**Pull request by netil**
## Issue
#100 

## Details

Updated 'How to use?' section to load packaged file.
Added note link for separate dependency file inclusion.

## Preferred reviewers
@happyhj @sculove

### CODE REVIEW

**Comment by netil** [comment]
Does anyone knows why latest download link is pointing gh-pages?
```html
For latest version, check out - https://github.com/naver/egjs/tree/gh-pages
```

**Comment by sculove** [comment]
umm... 
github.io does not support list of directory due to security.
therefore  we will prepare this task #26

fly @kishu

**Comment by sculove** [comment]
LGTM

**Comment by happyhj** [comment]
LGTM

**Comment by netil** [comment]
FYI, i updated download link as below.
- As-is: https://github.com/naver/egjs/tree/gh-pages
- To-be: https://github.com/naver/egjs/tree/gh-pages/latest/dist

If need change, let's open new issue for that. For now I'll merge as it.

**Pull request closed without merging**
