### PR TITLE
fix(flicking): Direction value not given during touch move

### PR DESCRIPTION
**Pull request by netil**
## Issue
#35 

## Details
Handle direction value when hammerEvent value exists.
Adjust direction value when moves on diagonal direction.

## Preferred reviewers
@sculove @taihoon-kim

### CODE REVIEW

**Comment by netil** [comment]
@mixed TC's are already added and described as 'Custom events #8 - Check for touch direction during hold'. And it doesn't necessarily add when hammerEvent isn't, because that is the normal case which current TC's are targeting.

**Comment by mixed** [comment]
1. When I ran tescase in `#8` It didn`t pass if-condition. if-condition is alway false.
2. Um... This case need to discuss with team.  Let talk to it next meeting.

Good Vacation~

**Comment by sculove** [comment]
그게 그거

**Comment by sculove** [comment]
LGTM

**Comment by sculove** [comment]
LGTM

**Comment by mixed** [comment]
LGTM

**Comment by sculove** [comment]
LGTM

**Pull request closed without merging**
